### ISSUE TITLE
Unable to import module 'lambda_function': No module named 'paramiko'

### ISSUE THREAD

**Issue by nimesh7424** [gpoudel/ssh-ec2-lambda#3]
Unable to import module 'lambda_function': No module named 'paramiko'

**Comment by gpoudel** [comment]
The zip file sshconn.zip is provided for the exact purpose - it contains the packages 'Request' and 'Paramiko'. You need to update the file  'lambda_function.py'  inside this zip and use it. Please follow all the steps mentioned in 'Readme.rmd'

**Comment by bandanadas1234** [comment]
I have  update the file 'lambda_function.py' inside this zip and followed 'Readme.rmd' file. However unfortunately still getting the error - Unable to import module 'lambda_function': No module named paramiko. Any help please
